name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env
      run: |
        if [ ! -f .env ]; then
          touch .env
          echo "${{secrets.PROD_ENV_FILE}}" > .env
        else
          echo ".env already exists"
        fi

    - name: Validate .env
      run: |
        if [ -z "$(cat .env)" ]; then
          echo "Error: .env file is empty or invalid."
          exit 1
        fi

    # - name: Export Environment Variables
    #   run:
    #     export $(grep -v '^#' .env | xargs)
    #     cat .env | while read line; do echo "$line" >> GITHUB_ENV; done    

    - name: Export Environment Variables
      run: |
        cat .env | while IFS= read -r line; do echo "$line" >> $GITHUB_ENV; done

    
    - name: Login to Docker Hub
      env:
         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: |
       docker build \
       $(cat .env | sed 's/^/--build-arg /') \
       -t jerinwilson/tickt-server .

    - name: Push the image to Docker Hub
      run: docker push jerinwilson/tickt-server:latest


     # deployment
  
  deploy:
    needs: build
    runs-on: self-hosted

    steps:

    - name: Pull the docker image from DockerHub
      run: sudo docker pull jerinwilson/tickt-server:latest

    - name: Delete old docker container
      run: sudo docker rm -f tickt-server-container || true

    - name: Run docker container with latest image
      run: |
        sudo docker run -d -p 8080:8080 --name tickt-server-container jerinwilson/tickt-server:latest